version: '3'
services:
    # apps
    sgb1:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: spring_boot_com_mysql/api
        container_name: sgb
        ports:
           - '8080:8080'
           - '465:465'
           - '25:25'
           - '5005:5005' # port debug
        environment:
           - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
           - PROFILE=dev
        links:
            - db
        depends_on:
          - "db"
        networks:
          - rede

    db:
        image: mysql:5.6
        container_name: db_container
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=sgb_dev
            - MYSQL_ROOT_PASSWORD=dev_pass
        volumes: 
            - ./docker/volume_mysql:/var/lib/mysql
        networks:
          - rede
networks:
  rede:
    driver: bridge